-- MySQL Script generated by MySQL Workbench
-- 11/26/15 00:17:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HL` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `HL` ;

-- -----------------------------------------------------
-- Table `HL`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Departamento` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `contador` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Decreto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Decreto` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) NOT NULL,
  `gaceta` VARCHAR(6) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Clientes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) NOT NULL,
  `direccion` TINYTEXT NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `encargado` VARCHAR(45) NOT NULL,
  `nRif` CHAR(10) NOT NULL,
  `cRif` CHAR(1) NOT NULL,
  `siglas` CHAR(4) NOT NULL,
  `contador` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Puesto` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`user` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `auth_key` VARCHAR(32) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `password_rest_token` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `status` SMALLINT(6) UNSIGNED NOT NULL DEFAULT 10,
  `created_at` INT(11) NOT NULL,
  `updated_at` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Vendedor` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Puesto_id` TINYINT UNSIGNED NOT NULL,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `Departamento_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Vendedor_Puesto_idx` (`Puesto_id` ASC),
  INDEX `fk_Vendedor_user1_idx` (`user_id` ASC),
  INDEX `fk_Vendedor_Departamento1_idx` (`Departamento_id` ASC),
  CONSTRAINT `fk_Vendedor_Puesto`
    FOREIGN KEY (`Puesto_id`)
    REFERENCES `HL`.`Puesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendedor_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `HL`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendedor_Departamento1`
    FOREIGN KEY (`Departamento_id`)
    REFERENCES `HL`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`General`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`General` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `copias` TINYINT UNSIGNED NOT NULL,
  `caudal` ENUM('Aplica', 'No Aplica') NOT NULL,
  `analisis` ENUM('Analisis y Muestreo', 'Analisis') NOT NULL,
  `Departamento_id` TINYINT UNSIGNED NOT NULL,
  `Decreto_id` TINYINT UNSIGNED NOT NULL,
  `Clientes_id` INT UNSIGNED NOT NULL,
  `Vendedor_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_General_Departamento1_idx` (`Departamento_id` ASC),
  INDEX `fk_General_Decreto1_idx` (`Decreto_id` ASC),
  INDEX `fk_General_Clientes1_idx` (`Clientes_id` ASC),
  INDEX `fk_General_Vendedor1_idx` (`Vendedor_id` ASC),
  CONSTRAINT `fk_General_Departamento1`
    FOREIGN KEY (`Departamento_id`)
    REFERENCES `HL`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_General_Decreto1`
    FOREIGN KEY (`Decreto_id`)
    REFERENCES `HL`.`Decreto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_General_Clientes1`
    FOREIGN KEY (`Clientes_id`)
    REFERENCES `HL`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_General_Vendedor1`
    FOREIGN KEY (`Vendedor_id`)
    REFERENCES `HL`.`Vendedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Tipo` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Muestras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Muestras` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo` BINARY(1) NOT NULL,
  `horas` TINYINT NOT NULL,
  `General_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Muestras_General1_idx` (`General_id` ASC),
  CONSTRAINT `fk_Muestras_General1`
    FOREIGN KEY (`General_id`)
    REFERENCES `HL`.`General` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Equipos` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `serial` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`CArea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`CArea` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` SMALLINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`SubTipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`SubTipo` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Decreto_has_Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Decreto_has_Tipo` (
  `Decreto_id` TINYINT UNSIGNED NOT NULL,
  `Tipo_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Decreto_id`, `Tipo_id`),
  INDEX `fk_Decreto_has_Tipo_Tipo1_idx` (`Tipo_id` ASC),
  INDEX `fk_Decreto_has_Tipo_Decreto1_idx` (`Decreto_id` ASC),
  CONSTRAINT `fk_Decreto_has_Tipo_Decreto1`
    FOREIGN KEY (`Decreto_id`)
    REFERENCES `HL`.`Decreto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Decreto_has_Tipo_Tipo1`
    FOREIGN KEY (`Tipo_id`)
    REFERENCES `HL`.`Tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Departamento_has_Decreto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Departamento_has_Decreto` (
  `Departamento_id` TINYINT UNSIGNED NOT NULL,
  `Decreto_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Departamento_id`, `Decreto_id`),
  INDEX `fk_Departamento_has_Decreto_Decreto1_idx` (`Decreto_id` ASC),
  INDEX `fk_Departamento_has_Decreto_Departamento1_idx` (`Departamento_id` ASC),
  CONSTRAINT `fk_Departamento_has_Decreto_Departamento1`
    FOREIGN KEY (`Departamento_id`)
    REFERENCES `HL`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Departamento_has_Decreto_Decreto1`
    FOREIGN KEY (`Decreto_id`)
    REFERENCES `HL`.`Decreto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Caracterizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Caracterizacion` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `preservacion` ENUM('0', '1', '2', '3', '4', '5', '6', '7', '8', '9') NOT NULL,
  `siglas` VARCHAR(15) NOT NULL,
  `laboratorio` ENUM('Si', 'No') NOT NULL,
  `opacidad` ENUM('Si', 'No') NOT NULL,
  `metodo` VARCHAR(15) NOT NULL,
  `tipo` ENUM('AceitesG', 'Cianuro', 'Cloruros', 'Dbo', 'Detergente', 'Dqo', 'Fenol', 'Formaldehido', 'FosforoAA', 'FosforoAV', 'Nitratos', 'Nitrito', 'Nitrogeno', 'NitrogenoA', 'Solidos', 'Sulfatos', 'Sulfitos', 'Sulfuro', 'Fluoruro', 'NitrogenoT', 'Ph', 'SolidosD', 'Conductividad', 'Salinidad', 'Color', 'Espuma', 'Turbidez', 'Acidez', 'DurezaT', 'Calcica', 'Magnesica', 'Alcalinidad') NOT NULL,
  `Equipos_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Caracterizacion_Equipos1_idx` (`Equipos_id` ASC),
  CONSTRAINT `fk_Caracterizacion_Equipos1`
    FOREIGN KEY (`Equipos_id`)
    REFERENCES `HL`.`Equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Rama`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Rama` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Caracterizacion_has_Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Caracterizacion_has_Departamento` (
  `Caracterizacion_id` SMALLINT UNSIGNED NOT NULL,
  `Departamento_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Caracterizacion_id`, `Departamento_id`),
  INDEX `fk_Caracterizacion_has_Departamento_Departamento1_idx` (`Departamento_id` ASC),
  INDEX `fk_Caracterizacion_has_Departamento_Caracterizacion1_idx` (`Caracterizacion_id` ASC),
  CONSTRAINT `fk_Caracterizacion_has_Departamento_Caracterizacion1`
    FOREIGN KEY (`Caracterizacion_id`)
    REFERENCES `HL`.`Caracterizacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Caracterizacion_has_Departamento_Departamento1`
    FOREIGN KEY (`Departamento_id`)
    REFERENCES `HL`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Rama_has_Caracterizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Rama_has_Caracterizacion` (
  `Rama_id` INT UNSIGNED NOT NULL,
  `Caracterizacion_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Rama_id`, `Caracterizacion_id`),
  INDEX `fk_Rama_has_Caracterizacion_Caracterizacion1_idx` (`Caracterizacion_id` ASC),
  INDEX `fk_Rama_has_Caracterizacion_Rama1_idx` (`Rama_id` ASC),
  CONSTRAINT `fk_Rama_has_Caracterizacion_Rama1`
    FOREIGN KEY (`Rama_id`)
    REFERENCES `HL`.`Rama` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rama_has_Caracterizacion_Caracterizacion1`
    FOREIGN KEY (`Caracterizacion_id`)
    REFERENCES `HL`.`Caracterizacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Limites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Limites` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `liminf` FLOAT NOT NULL,
  `limsup` FLOAT NOT NULL,
  `existente` ENUM('Si', 'No') NOT NULL,
  `Departamento_id` TINYINT UNSIGNED NOT NULL,
  `Decreto_id` TINYINT UNSIGNED NOT NULL,
  `Tipo_id` TINYINT UNSIGNED NOT NULL,
  `SubTipo_id` TINYINT UNSIGNED NOT NULL,
  `Caracterizacion_id` SMALLINT UNSIGNED NOT NULL,
  `Rama_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Limites_Departamento1_idx` (`Departamento_id` ASC),
  INDEX `fk_Limites_Decreto1_idx` (`Decreto_id` ASC),
  INDEX `fk_Limites_Tipo1_idx` (`Tipo_id` ASC),
  INDEX `fk_Limites_SubTipo1_idx` (`SubTipo_id` ASC),
  INDEX `fk_Limites_Caracterizacion1_idx` (`Caracterizacion_id` ASC),
  INDEX `fk_Limites_Rama1_idx` (`Rama_id` ASC),
  CONSTRAINT `fk_Limites_Departamento1`
    FOREIGN KEY (`Departamento_id`)
    REFERENCES `HL`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Limites_Decreto1`
    FOREIGN KEY (`Decreto_id`)
    REFERENCES `HL`.`Decreto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Limites_Tipo1`
    FOREIGN KEY (`Tipo_id`)
    REFERENCES `HL`.`Tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Limites_SubTipo1`
    FOREIGN KEY (`SubTipo_id`)
    REFERENCES `HL`.`SubTipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Limites_Caracterizacion1`
    FOREIGN KEY (`Caracterizacion_id`)
    REFERENCES `HL`.`Caracterizacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Limites_Rama1`
    FOREIGN KEY (`Rama_id`)
    REFERENCES `HL`.`Rama` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Parametros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Parametros` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `General_id` INT UNSIGNED NOT NULL,
  `Limites_id` MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Parametros_General1_idx` (`General_id` ASC),
  INDEX `fk_Parametros_Limites1_idx` (`Limites_id` ASC),
  CONSTRAINT `fk_Parametros_General1`
    FOREIGN KEY (`General_id`)
    REFERENCES `HL`.`General` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Parametros_Limites1`
    FOREIGN KEY (`Limites_id`)
    REFERENCES `HL`.`Limites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Equipos_has_General`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Equipos_has_General` (
  `Equipos_id` SMALLINT UNSIGNED NOT NULL,
  `General_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Equipos_id`, `General_id`),
  INDEX `fk_Equipos_has_General_General1_idx` (`General_id` ASC),
  INDEX `fk_Equipos_has_General_Equipos1_idx` (`Equipos_id` ASC),
  CONSTRAINT `fk_Equipos_has_General_Equipos1`
    FOREIGN KEY (`Equipos_id`)
    REFERENCES `HL`.`Equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipos_has_General_General1`
    FOREIGN KEY (`General_id`)
    REFERENCES `HL`.`General` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Moneda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Moneda` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `conversion` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`CostoPredeterminados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`CostoPredeterminados` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `costo` FLOAT NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  `vencimiento` TINYINT UNSIGNED NOT NULL,
  `Moneda_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CostoPredeterminados_Moneda1_idx` (`Moneda_id` ASC),
  CONSTRAINT `fk_CostoPredeterminados_Moneda1`
    FOREIGN KEY (`Moneda_id`)
    REFERENCES `HL`.`Moneda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Rama_has_General`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Rama_has_General` (
  `Rama_id` INT UNSIGNED NOT NULL,
  `General_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Rama_id`, `General_id`),
  INDEX `fk_Rama_has_General_General1_idx` (`General_id` ASC),
  INDEX `fk_Rama_has_General_Rama1_idx` (`Rama_id` ASC),
  CONSTRAINT `fk_Rama_has_General_Rama1`
    FOREIGN KEY (`Rama_id`)
    REFERENCES `HL`.`Rama` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rama_has_General_General1`
    FOREIGN KEY (`General_id`)
    REFERENCES `HL`.`General` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Parametros_has_Muestras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Parametros_has_Muestras` (
  `Parametros_id` INT UNSIGNED NOT NULL,
  `Muestras_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Parametros_id`, `Muestras_id`),
  INDEX `fk_Parametros_has_Muestras_Muestras1_idx` (`Muestras_id` ASC),
  INDEX `fk_Parametros_has_Muestras_Parametros1_idx` (`Parametros_id` ASC),
  CONSTRAINT `fk_Parametros_has_Muestras_Parametros1`
    FOREIGN KEY (`Parametros_id`)
    REFERENCES `HL`.`Parametros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Parametros_has_Muestras_Muestras1`
    FOREIGN KEY (`Muestras_id`)
    REFERENCES `HL`.`Muestras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Plantilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Plantilla` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reporte` TEXT NOT NULL,
  `Vendedor_id` TINYINT UNSIGNED NOT NULL,
  `Departamento_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reporte_Vendedor1_idx` (`Vendedor_id` ASC),
  INDEX `fk_reporte_Departamento1_idx` (`Departamento_id` ASC),
  CONSTRAINT `fk_reporte_Vendedor1`
    FOREIGN KEY (`Vendedor_id`)
    REFERENCES `HL`.`Vendedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_Departamento1`
    FOREIGN KEY (`Departamento_id`)
    REFERENCES `HL`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT(11) NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`track`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`track` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `session` VARCHAR(100) NOT NULL,
  `date` DATETIME NOT NULL,
  `ip` VARCHAR(15) NOT NULL,
  `user_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_track_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_track_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `HL`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Referencia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ano` YEAR NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`DiaLaborables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`DiaLaborables` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dias` DATE NOT NULL,
  `Referencia_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_diaLaborables_referencia1_idx` (`Referencia_id` ASC),
  CONSTRAINT `fk_diaLaborables_referencia1`
    FOREIGN KEY (`Referencia_id`)
    REFERENCES `HL`.`Referencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Reporte` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Plantilla_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reporte_Plantilla1_idx` (`Plantilla_id` ASC),
  CONSTRAINT `fk_reporte_Plantilla1`
    FOREIGN KEY (`Plantilla_id`)
    REFERENCES `HL`.`Plantilla` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Costos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Costos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cAnalisis` FLOAT NOT NULL,
  `cMuestreo` FLOAT NOT NULL,
  `cInforme` FLOAT NOT NULL,
  `cAdministrativo` FLOAT NOT NULL,
  `utilidad` FLOAT NOT NULL,
  `rendimiento` TINYINT NOT NULL,
  `General_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Costos_General1_idx` (`General_id` ASC),
  CONSTRAINT `fk_Costos_General1`
    FOREIGN KEY (`General_id`)
    REFERENCES `HL`.`General` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Peticion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Peticion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fPeticion` DATE NOT NULL,
  `cadena` VARCHAR(15) NOT NULL,
  `fVencimiento` TINYINT UNSIGNED NOT NULL,
  `fCreacion` TIMESTAMP NOT NULL DEFAULT now(),
  `Referencia_id` INT UNSIGNED NOT NULL,
  `General_id` INT UNSIGNED NOT NULL,
  `Muestras_id` INT UNSIGNED NOT NULL,
  `Costos_id` INT UNSIGNED NOT NULL,
  `Reporte_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `General_id`, `Muestras_id`, `Referencia_id`),
  INDEX `fk_peticion_referencia1_idx` (`Referencia_id` ASC),
  INDEX `fk_peticion_General1_idx` (`General_id` ASC),
  INDEX `fk_peticion_Muestras1_idx` (`Muestras_id` ASC),
  INDEX `fk_Peticion_Costos1_idx` (`Costos_id` ASC),
  INDEX `fk_Peticion_Reporte1_idx` (`Reporte_id` ASC),
  CONSTRAINT `fk_peticion_referencia1`
    FOREIGN KEY (`Referencia_id`)
    REFERENCES `HL`.`Referencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peticion_General1`
    FOREIGN KEY (`General_id`)
    REFERENCES `HL`.`General` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peticion_Muestras1`
    FOREIGN KEY (`Muestras_id`)
    REFERENCES `HL`.`Muestras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peticion_Costos1`
    FOREIGN KEY (`Costos_id`)
    REFERENCES `HL`.`Costos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peticion_Reporte1`
    FOREIGN KEY (`Reporte_id`)
    REFERENCES `HL`.`Reporte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`OrdenCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`OrdenCompra` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nOrden` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(150) NOT NULL,
  `observaciones` TEXT NOT NULL,
  `estado` ENUM('Rechazado', 'Pendiente', 'Aceptada') NOT NULL,
  `Peticion_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ordenCompra_peticion1_idx` (`Peticion_id` ASC),
  CONSTRAINT `fk_ordenCompra_peticion1`
    FOREIGN KEY (`Peticion_id`)
    REFERENCES `HL`.`Peticion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Caracterizacion_has_Equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Caracterizacion_has_Equipos` (
  `Caracterizacion_id` SMALLINT UNSIGNED NOT NULL,
  `Equipos_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Caracterizacion_id`, `Equipos_id`),
  INDEX `fk_Caracterizacion_has_Equipos_Equipos1_idx` (`Equipos_id` ASC),
  INDEX `fk_Caracterizacion_has_Equipos_Caracterizacion1_idx` (`Caracterizacion_id` ASC),
  CONSTRAINT `fk_Caracterizacion_has_Equipos_Caracterizacion1`
    FOREIGN KEY (`Caracterizacion_id`)
    REFERENCES `HL`.`Caracterizacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Caracterizacion_has_Equipos_Equipos1`
    FOREIGN KEY (`Equipos_id`)
    REFERENCES `HL`.`Equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`General_has_Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`General_has_Tipo` (
  `General_id` INT UNSIGNED NOT NULL,
  `Tipo_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`General_id`, `Tipo_id`),
  INDEX `fk_General_has_Tipo_Tipo1_idx` (`Tipo_id` ASC),
  INDEX `fk_General_has_Tipo_General1_idx` (`General_id` ASC),
  CONSTRAINT `fk_General_has_Tipo_General1`
    FOREIGN KEY (`General_id`)
    REFERENCES `HL`.`General` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_General_has_Tipo_Tipo1`
    FOREIGN KEY (`Tipo_id`)
    REFERENCES `HL`.`Tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`codigoMuestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`codigoMuestra` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`codigoAnalisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`codigoAnalisis` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Celular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Celular` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero` MEDIUMINT(7) UNSIGNED NOT NULL,
  `CArea_id` TINYINT UNSIGNED NOT NULL,
  `Clientes_id` INT UNSIGNED NULL,
  `Vendedor_id` TINYINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Celular_CArea1_idx` (`CArea_id` ASC),
  INDEX `fk_Celular_Clientes1_idx` (`Clientes_id` ASC),
  INDEX `fk_Celular_Vendedor1_idx` (`Vendedor_id` ASC),
  CONSTRAINT `fk_Celular_CArea1`
    FOREIGN KEY (`CArea_id`)
    REFERENCES `HL`.`CArea` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Celular_Clientes1`
    FOREIGN KEY (`Clientes_id`)
    REFERENCES `HL`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Celular_Vendedor1`
    FOREIGN KEY (`Vendedor_id`)
    REFERENCES `HL`.`Vendedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Tipo_has_SubTipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Tipo_has_SubTipo` (
  `Tipo_id` TINYINT UNSIGNED NOT NULL,
  `SubTipo_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Tipo_id`, `SubTipo_id`),
  INDEX `fk_Tipo_has_SubTipo_SubTipo1_idx` (`SubTipo_id` ASC),
  INDEX `fk_Tipo_has_SubTipo_Tipo1_idx` (`Tipo_id` ASC),
  CONSTRAINT `fk_Tipo_has_SubTipo_Tipo1`
    FOREIGN KEY (`Tipo_id`)
    REFERENCES `HL`.`Tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tipo_has_SubTipo_SubTipo1`
    FOREIGN KEY (`SubTipo_id`)
    REFERENCES `HL`.`SubTipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`General_has_SubTipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`General_has_SubTipo` (
  `General_id` INT UNSIGNED NOT NULL,
  `SubTipo_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`General_id`, `SubTipo_id`),
  INDEX `fk_General_has_SubTipo_SubTipo1_idx` (`SubTipo_id` ASC),
  INDEX `fk_General_has_SubTipo_General1_idx` (`General_id` ASC),
  CONSTRAINT `fk_General_has_SubTipo_General1`
    FOREIGN KEY (`General_id`)
    REFERENCES `HL`.`General` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_General_has_SubTipo_SubTipo1`
    FOREIGN KEY (`SubTipo_id`)
    REFERENCES `HL`.`SubTipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Parametros_has_Muestras_has_CostoPredeterminados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Parametros_has_Muestras_has_CostoPredeterminados` (
  `Parametros_has_Muestras_Parametros_id` INT UNSIGNED NOT NULL,
  `Parametros_has_Muestras_Muestras_id` INT UNSIGNED NOT NULL,
  `CostoPredeterminados_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Parametros_has_Muestras_Parametros_id`, `Parametros_has_Muestras_Muestras_id`, `CostoPredeterminados_id`),
  INDEX `fk_Parametros_has_Muestras_has_CostoPredeterminados_CostoPr_idx` (`CostoPredeterminados_id` ASC),
  INDEX `fk_Parametros_has_Muestras_has_CostoPredeterminados_Paramet_idx` (`Parametros_has_Muestras_Parametros_id` ASC, `Parametros_has_Muestras_Muestras_id` ASC),
  CONSTRAINT `fk_Parametros_has_Muestras_has_CostoPredeterminados_Parametro1`
    FOREIGN KEY (`Parametros_has_Muestras_Parametros_id` , `Parametros_has_Muestras_Muestras_id`)
    REFERENCES `HL`.`Parametros_has_Muestras` (`Parametros_id` , `Muestras_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Parametros_has_Muestras_has_CostoPredeterminados_CostoPred1`
    FOREIGN KEY (`CostoPredeterminados_id`)
    REFERENCES `HL`.`CostoPredeterminados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`CostoPredeterminados_has_Parametros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`CostoPredeterminados_has_Parametros` (
  `CostoPredeterminados_id` INT UNSIGNED NOT NULL,
  `Parametros_id` INT UNSIGNED NOT NULL,
  `cantidad` FLOAT NOT NULL,
  `k` FLOAT NOT NULL,
  `unidad` ENUM('equipos', 'materiales', 'mano') NOT NULL,
  PRIMARY KEY (`CostoPredeterminados_id`, `Parametros_id`),
  INDEX `fk_CostoPredeterminados_has_Parametros_Parametros1_idx` (`Parametros_id` ASC),
  INDEX `fk_CostoPredeterminados_has_Parametros_CostoPredeterminados_idx` (`CostoPredeterminados_id` ASC),
  CONSTRAINT `fk_CostoPredeterminados_has_Parametros_CostoPredeterminados1`
    FOREIGN KEY (`CostoPredeterminados_id`)
    REFERENCES `HL`.`CostoPredeterminados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CostoPredeterminados_has_Parametros_Parametros1`
    FOREIGN KEY (`Parametros_id`)
    REFERENCES `HL`.`Parametros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Administrativos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Administrativos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `total` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`CostoPredeterminados_has_Administrativos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`CostoPredeterminados_has_Administrativos` (
  `CostoPredeterminados_id` INT UNSIGNED NOT NULL,
  `Administrativos_id` INT UNSIGNED NOT NULL,
  `cantidad` FLOAT NOT NULL,
  `dias` FLOAT NOT NULL,
  PRIMARY KEY (`CostoPredeterminados_id`, `Administrativos_id`),
  INDEX `fk_CostoPredeterminados_has_Administrativos_Administrativos_idx` (`Administrativos_id` ASC),
  INDEX `fk_CostoPredeterminados_has_Administrativos_CostoPredetermi_idx` (`CostoPredeterminados_id` ASC),
  CONSTRAINT `fk_CostoPredeterminados_has_Administrativos_CostoPredetermina1`
    FOREIGN KEY (`CostoPredeterminados_id`)
    REFERENCES `HL`.`CostoPredeterminados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CostoPredeterminados_has_Administrativos_Administrativos1`
    FOREIGN KEY (`Administrativos_id`)
    REFERENCES `HL`.`Administrativos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Prestaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Prestaciones` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`Constantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`Constantes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) NOT NULL,
  `cantidad` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HL`.`CostoPredeterminados_has_Prestaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HL`.`CostoPredeterminados_has_Prestaciones` (
  `CostoPredeterminados_id` INT UNSIGNED NOT NULL,
  `Prestaciones_id` INT UNSIGNED NOT NULL,
  `Constantes_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`CostoPredeterminados_id`, `Prestaciones_id`),
  INDEX `fk_CostoPredeterminados_has_Prestaciones_Prestaciones1_idx` (`Prestaciones_id` ASC),
  INDEX `fk_CostoPredeterminados_has_Prestaciones_CostoPredeterminad_idx` (`CostoPredeterminados_id` ASC),
  INDEX `fk_CostoPredeterminados_has_Prestaciones_Constantes1_idx` (`Constantes_id` ASC),
  CONSTRAINT `fk_CostoPredeterminados_has_Prestaciones_CostoPredeterminados1`
    FOREIGN KEY (`CostoPredeterminados_id`)
    REFERENCES `HL`.`CostoPredeterminados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CostoPredeterminados_has_Prestaciones_Prestaciones1`
    FOREIGN KEY (`Prestaciones_id`)
    REFERENCES `HL`.`Prestaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CostoPredeterminados_has_Prestaciones_Constantes1`
    FOREIGN KEY (`Constantes_id`)
    REFERENCES `HL`.`Constantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
